export const description = [
    {id: 1, title: 'The Original Green Monster Energy', description: "Tear into a can of the meanest energy drink on the planet, Monster Energy. It's the ideal combo of the right ingredients in the right proportion to deliver the big bad buzz that only Monster can. Monster packs a powerful punch but has a smooth easy drinking flavor. Athletes, musicians, anarchists, co-ed’s, road warriors, metal heads, geeks, hipsters, and bikers dig it- you will too."},
    {id: 2, title: 'The Original Lo-Carb Monster Energy', description: "Tear into a can of the meanest energy drink on the planet, Lo-carb Monster Energy. Low calories, no compromise. That’s what Lo-carb Monster Energy is all about. Get the big bad Monster buzz you know and love, but with a fraction of the calories and carbohydrates. Athletes, musicians, anarchists, co-ed’s, road warriors, metal heads, geeks, hipsters, and bikers dig it- you will too."},
    {id: 3, title: 'Zero Sugar Monster Energy', description: "People have been blowin' up our inbox for years asking for a zero sugar Monster. We got it but this ain't soda pop, dude! Making a zero sugar drink, that's good enough to earn the Monster M ain't that easy. Finally, with a re-tooled energy blend, new sweetener system and after hundreds of failed flavors, we got it right! Monster Zero Sugar: helps fight fatigue, improve mental performance and focus, and motivates you to work (I mean play) harder, so generally you feel pretty damn good. Zero sugar, Monster buzz..."},
    {id: 4, title: 'The Original Green Monster Energy 269ml', description: "Tear into a can of the meanest energy drink on the planet, Monster Energy. It's the ideal combo of the right ingredients in the right proportion to deliver the big bad buzz that only Monster can. Monster packs a powerful punch but has a smooth easy drinking flavor. Athletes, musicians, anarchists, co-ed’s, road warriors, metal heads, geeks, hipsters, and bikers dig it- you will too."},
    {id: 5, title: 'Zero Ultra a.k.a. The White Monster', description: "Some people are impossible to please. As soon as they get what they thought they wanted they always want more. Our team riders and Monster Girls are no different… they’ve been dropping some hints lately.They’ve been asking us for a new Monster drink. A little less sweet; lighter-tasting, zero sugar, but with a full load of our Monster energy blend. Sure, white is the new black. We went all out: Monster Energy Zero Ultra."},
    {id: 6, title: 'Zero-Sugar Ultra Violet a.k.a. The Purple Monster', description: "Welcome to the 70's. A hazy purple funk all dressed up in a kaleidoscope of bell bottoms, bandanas, and tie-dye. A time when psychedelic, glam and heavy metal rock blasted from mega speakers at fairgrounds, stadiums and garages. Can you dig it? The take a good long pull of Monster Ultra Violet. Crisp and refreshing, with a sweet and tart pixie dust flavor powered with our Monster Energy Blend. Hop on this Purple Monster for the ride!"},
    {id: 7, title: 'Zero-Sugar Ultra Paradise', description: "Where is paradise? A chalet on the slopes, a stream side ranch or a penthouse in the city, How about a private island with a white sand beach, turquoise water and a gentle tropical breeze. Monster Ultra Paradise, sugar free, pure, crisp, invigorating island flavors. Kick back and enjoy, Monster Paradise is wherever you can find it!"},
    {id: 8, title: 'Juice Monster Mango Loco', description: `Following Halloween each year friends and family gather to celebrate "Dia de Los Muertos". Marigolds, mysticism and memories combined with food and drink entice the souls of the departed to join the party. Mango Loco is a heavenly blend of exotic juices certain to attract even the most stubborn spirit. Crazy good taste with just enough of that Monster magic to keep the party going for days…`},
    {id: 9, title: 'Juice Monster Pacific Punch', description: "Hawaiian it’s not! Lighter, less sweet and more complex. A flavor as deep and wide as its name sake the great Pacific. Naturally we added our Monster Energy Blend to help put wind in your Sails and keep you steady and on course no matter how rough the seas. Pacific Punch your adventure awaits arrgh…"},
    {id: 10, title: 'Juice Monster Khaotic',  description: `Back in “05” the original Juice Monster shook-up the game by combining great-tasting real juice with energy drink functionality and attitude. Now over a decade later, we decided it was time for a little makeover of the classic. We lightened-up the flavor and adjusted the juice blend to create a taste that is better experienced than described. Of course, our Monster Energy DNA remains unchanged. For our new paint job, we called on longtime friend and legendary street artist Risk. His iconic west coast style and vibrant presentation perfectly capture the spirit of our original Khaos reborn as Khaotic!`},
    {id: 11, title: 'Monster Dragon Iced Tea: Lemon Tea',  description: "According to legend Chinese Emperor Shennong accidentally discovered tea when a divine wind blew some leaves into his boiling water. Enter the dragon...5000 years later we use only the finest ingredients in Dragon Iced Tea, so it's fit for an emperor or empress but available to all.  Dragon Iced Tea is light and refreshing with 100 calories per can. Formulated with energy boosting ingredients for a distinctly modern twist on the original. A new legend is born."},
    {id: 12, title: 'Monster Dragon Iced Tea: Peach Tea',  description: "According to legend Chinese Emperor Shennong accidentally discovered tea when a divine wind blew some leaves into his boiling water. Enter the dragon...5000 years later we use only the finest ingredients in Dragon Iced Tea, so it's fit for an emperor or empress but available to all.  Dragon Iced Tea is light and refreshing with 100 calories per can. Formulated with energy boosting ingredients for a distinctly modern twist on the original. A new legend is born."}
]